Repository jbl0107/decide-single-mulhacen-2, pull requests merged in 2022-12, with the labels that each got.

#88 Juamenvar
  Plantilla gestión de incidencias
  decide/visualizer/views.py
Labels: code

#123 #121 Personalizar GitHub Actions
  .github/workflows/django.yml
Labels: code, high priority

#132 ER Corrección de pequeños fallos
  decide/visualizer/views.py
Labels: bug, code

#144 #95 Tests de visualizer implementados todos
  decide/visualizer/tests.py
Labels: code

#147 #133 Tests página ETSII: Realizados
  decide/nuevaInfo/templates/nuevaInfo/infoETSII.html
  decide/nuevaInfo/tests.py
Labels: code, high priority

#155 #134 Crear test de traducción de página jornadas
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/nuevaInfo/templates/nuevaInfo/infoJornadas.html
  decide/nuevaInfo/tests.py
  decide/voting/tests.py
Labels: code, high priority

#161 #160 Comentar test de store y mixnet
  decide/mixnet/tests.py
  decide/store/tests.py
Labels: bug, code, medium priority
